name: Goragitize
on:
  push:
    branches: [main]
jobs:
  job:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          # These options must be set
          fetch-depth: 0
          persist-credentials: false

      - uses: narze/goragit@main
        with:
          author_name: potbye
          author_email: potbye@users.noreply.github.com
          github_token_with_repo_scope: ${{ secrets.GH_TOKEN_WITH_REPO_SCOPE }}
          i_understand_that_this_workflow_will_goragodize_my_repo: true
          keep_git_history_in_message: false # Optional
